# Generated by Django 5.1.13 on 2025-10-05 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Nombre o descripción del evento', max_length=200)),
                ('event_date', models.DateTimeField(help_text='Fecha y hora del evento')),
                ('location_name', models.CharField(blank=True, help_text='Nombre del lugar', max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('weather_data', models.JSONField(blank=True, help_text='Datos meteorológicos completos de la API', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperatura en °C', null=True)),
                ('precipitation', models.FloatField(blank=True, help_text='Precipitación en mm', null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='Velocidad del viento en km/h', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agents.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['user', 'event_date'], name='events_user_id_d1ad79_idx'), models.Index(fields=['event_date'], name='events_event_d_ec8074_idx')],
            },
        ),
    ]
