# Generated by Django 5.1.13 on 2025-10-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prob_snowfall',
            field=models.FloatField(blank=True, help_text='Probabilidad de nevada en %', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='snow_depth',
            field=models.FloatField(blank=True, help_text='Profundidad de nieve en cm', null=True),
        ),
    ]
